apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  annotations:
    anywhere.eks.amazonaws.com/management-components-version: v0.20.0-dev+build.177
  name: main-i-09a06-2c27bc6
  namespace: default
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
    machineHealthCheck:
      maxUnhealthy: 100%
  datacenterRef:
    kind: DockerDatacenterConfig
    name: main-i-09a06-2c27bc6
  eksaVersion: v0.20.0-dev+build.177
  externalEtcdConfiguration:
    count: 1
  gitOpsRef:
    kind: FluxConfig
    name: eksa-test
  kubernetesVersion: "1.28"
  machineHealthCheck:
    maxUnhealthy: 100%
    nodeStartupTimeout: 10m0s
    unhealthyMachineTimeout: 5m0s
  managementCluster:
    name: main-i-09a06-2c27bc6
  workerNodeGroupConfigurations:
  - count: 3
    machineHealthCheck:
      maxUnhealthy: 40%
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: DockerDatacenterConfig
metadata:
  name: main-i-09a06-2c27bc6
  namespace: default
spec: {}

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: eksa-test
  namespace: default
spec:
  branch: aws-eks-anywhere-test-docker-ff816adb-3847-46e1-9427-9da62ffd1646-3
  clusterConfigPath: aws-eks-anywhere-test-docker-ff816adb-3847-46e1-9427-9da62ffd1646-3
  git:
    repositoryUrl: ssh://git@github.com/that-jetpack-guy/aws-eks-anywhere-test-docker-ff816adb-3847-46e1-9427-9da62ffd1646-3.git
  systemNamespace: default

---
